### PR TITLE
Post data

### PR DESCRIPTION
**Pull request by janzeleny**
There are some problems when the proxy is used to forward POST, PUT and DELETE data. First of all, converting query string to the content is not right, as it might cause problems in some remote scripts that expect the data to be at the original place. Second of all, if there is a content sent in the original request, the content is lost in the forwarded request. This proposed pull request fixes both these issues, plus it adds support for json content.

### CODE REVIEW

**Comment by janzeleny** [comment]
I see that Travis testing has failed. I now wonder if it's possible under any circumstances to receive a request object without any headers. Looking at the symfony code, I don't think it's possible. Have you encountered any situation where headers were set to null? If not, perhaps the best solution would be to update the test suite? Or should I fix the problem by testing for null value in the headers field?

**Comment by gonzalo123** [comment]
I don't understand the problem you are trying to solve with this, maybe a unit test to explain the problem would be great. 

Anyway I think with this line existing unit tests won't fail. I need to check it out 

$contentType = is_null($this->request->headers) ? NULL : $this->request->headers->get('content-type');

Another problem is that we're using too many arguments within funcitons. According to Uncle's Bob's "Cean Code" Book more than 3 is a code smell. It works, I known, and refactors can look line over-engineering here.

**Comment by janzeleny** [comment]
> I don't understand the problem you are trying to solve with this, maybe
> a unit test to explain the problem would be great.

The problem is simple: when the proxy receives a POST or PUT request, I
would like it to forward the request exactly as it was received. The
current code doesn't do that.

> Anyway I think with this line existing unit tests won't fail. I need to
> check it out
> 
> $contentType = is_null($this->request->headers) ? NULL :
> $this->request->headers->get('content-type');

You are absolutely right. But the point I was trying to make is that the
headers field can actually never be null in real life scenarios, at
least that's what I observed in the code of Symfony. In that case the
unit test would be incorrect. However, I am not completely sure that my
hypothesis is correct, that's why I was asking you if you are familiar
with any situation where the headers can actually be null - I just want
to know if I should patch my code or the unit test.

> Another problem is that we're using too many arguments within funcitons.
> According to Uncle's Bob's "Cean Code" Book more than 3 is a code smell.
> It works, I known, and refactors can look line over-engineering here.

I must say I am a bit unsure about this. Do you have any specific ideas
how to refactor this? I am willing to give it a shot. I was thinking
about abstracting content and contentType into a dedicated type, but
that really is over-engineering, as it shrinks just two arguments into
one, with no potential for the new code to be re-used.

Personally, I would recommend to be practical for the time being and
tolerate the extra argument. If the code in this area grows
substantially, it will be definitely a good idea to refactor it but at
this point the idea seems rather academical.

Thanks a lot for the feedback and I look forward to continue the
conversation. Let me know what do you think about my comments.

Regards
Jan

**Comment by janzeleny** [comment]
Ok, so I added the check for null value in headers, as I did not manage to figure out how is it possible that the value is empty. I suppose it can be empty in some cases, therefore the detection is appropriate.

**Comment by gonzalo123** [comment]
The main problem with extra parameters is that the turn readable code into un-readable one.  Especially bolean values. I must admit after reading Clean Code time ago I turn myself into a bit paranoid. But the real problem is that Uncle Bob convinced me :)

**Pull request merged**
